### PR TITLE
Fix for multiprocessing

### PR DESCRIPTION
**Pull request by F1ashhimself**
Fix to work correctly with [multiprocess nose plugin](http://nose.readthedocs.org/en/latest/plugins/multiprocess.html).

### CODE REVIEW

**Comment by dmakhno** [comment]
@F1ashhimself, @sergeychipiga, I have issues with v1.0.2
When I run from console logdir - is empty, none of xml is generated.
When debug at 
L81
```python
self.allure.impl.stop_suite()
```
I do see that files are generated and actually they exists.
And as I can see one file per test.

I have really dummy suite, and my run looks exactly:
`nosetests --processes=8 --process-timeout=6000 --with-allure --logdir=allure-results`

Just in case here is how dummy suite looks:
```python
class Dummy(unittest.TestCase):

    def clean(self):
        pass

    def test_pass(self):
        pass

    def test_random(self):
        i = random.random()
        assert i < 0.5

    def test_random2(self):
        i = random.random()
        assert i > 0.5

    def test_clean_good(self):
        self.addCleanup(lambda: self.clean())

    def test_clean_bad(self):
        self.addCleanup(lambda: self.clean())
        assert False

class Dummy2(Dummy):
    def test_pass_2(self):
        pass
    def test_pass_3(self):
        pass

class Dummy3(Dummy):
    def test_pass_2(self):
        pass
    def test_pass_3(self):
        pass

class DummyMoreFail(Dummy):
    def test_fail_less(self):
        i = random.random()
        assert i < 0.3
    def test_fail_more(self):
        i = random.random()
        assert i > 0.7
```

**Comment by sergeychipiga** [comment]
@dmakhno thank you for your report! Will try to fix as quick as possible

**Comment by dmakhno** [comment]
@sergeychipiga, thanks in advance.
No hurry with me, one-process version works fine. I just monitoring the moment to start using it.

**Comment by F1ashhimself** [comment]
@dmakhno, hi there.

Issues that you described is somewhere in logic of [nose multiprocessing plugin](https://github.com/nose-devs/nose) and [allure pytest adaptor](https://github.com/allure-framework/allure-python)

This can be also reproduced with smaller script:
```(python)
import unittest


class Dummy(unittest.TestCase):

    def test_foo(self):
        assert False, 'Bar'
```

The main point is that you using 8 workers and each worker will be initialized in separate thread so ```nose_allure.Allure#configure``` method will be executed multiple times and AllureImpl will be 
initiated multiple times too, this will cause of clearing allure log folder repeatedly. The issue appears when your test will be completed before the last worker was initialized. 

So, I think, there is nothing that we can do from this (allure-nose-adaptor) side. You can try to set up a little less workers (processes).

Please let me know if you have any suggestions about this.

**Comment by dmakhno** [comment]
Maybe Allure should clear folder only when initialised in "root" and for multiprocess in [_instantiate_plugins](http://nose.readthedocs.org/en/latest/plugins/multiprocess.html) do not call folder cleaning?
My expectations that in multiprocess there is special plugin for each worker, that works in similar way... and this should (somehow) resolve issue "one testcase per one file".

... I'll try to play with it on weekend, but I'm far away understanding all magic nose and allure does.

**Comment by dmakhno** [comment]
or what [xunitmp](https://github.com/Ignas/nose_xunitmp) does.
because xunit had similar issue, xunitmp uses global [multiprocessing dict](https://github.com/Ignas/nose_xunitmp/blob/master/nose_xunitmp.py#L12) to sync threads.

**Comment by F1ashhimself** [comment]
@dmakhno [allure-python](https://github.com/allure-framework/allure-python) is a different project.
```_instantiate_plugins``` variable is empty when you running your tests (your case), you can add there some test that will not enabled earlier.

Also each test is another worker, allure, file, but if they have the same name this will be one suite in html report, so I cant understand what issue are you talking about.

I will look into ```xunitmp``` implementation for this. Thank ya!

**Comment by dmakhno** [comment]
> Also each test is another worker
Actually it depends.
On default xunit like tests, are grouped per worker. This way setupClass will be called once and all tests will withing same worker and rely on result of setupClass. And thus suite can be withing one file, imho.

But you can play with `_multiprocess_can_split_` True, this way each test may be executed on different worker (and get painful result for integration tests when setupClass executed several times)

**Comment by dmakhno** [comment]
if it important here is my old playground how tests are split
https://gist.github.com/dmakhno/9970080#file-test_parallel-py

**Comment by F1ashhimself** [comment]
@dmakhno I have looked into xunitmp code and they have the same issue, you can verify it by running my short test ```class Dummy``` that I gave you abow with parameters ```--processes=8 --process-timeout=6000 --with-xunitmp``` and you will see that ```nosetests.xml``` file will have ```<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="0" errors="0" failures="0" skip="0"></testsuite>```.

**Pull request merged**
